import numpy as np
import pandas as pd
from simpledbf import Dbf5
from bamboo_lib.connectors.models import Connector
from bamboo_lib.models import EasyPipeline, PipelineStep, Parameter
from bamboo_lib.steps import LoadStep

from ene_01 import Module1Step
from ene_02_01 import Module21Step
from ene_02_02 import Module22Step
# from ene_03_01 import Module31Step
# from ene_03_02 import Module32Step
# from ene_04_01 import Module41Step
from ene_04_02 import Module42Step
from ene_05 import Module5Step

class JoinStep(PipelineStep):
    def run_step(self, prev, params):

      # df, mod2_1, mod2_2, mod4_1, mod4_2, mod5_1, mod5_2, mod6 = prev
      df, mod2_1, mod2_2, mod5_2, mod6 = prev

      #for dataset in [mod2_1, mod2_2, mod4_1, mod4_2, mod5_1, mod5_2, mod6]:
      for dataset in [mod2_1, mod2_2, mod5_2, mod6]:
         df = df.merge(dataset, on='company_id')

      df['year'] = 2015

      expanded_columns = [
        'n_ejecutivos_hombres',
        'n_ejecutivos_mujeres',
        'n_empleados_permanentes_hombres',
        'n_empleados_permanentes_mujeres',
        'n_obreros_permanentes_hombres',
        'n_obreros_permanentes_mujeres',
        'n_empleados_eventuales_hombres',
        'n_empleados_eventuales_mujeres',
        'n_obreros_eventuales_hombres',
        'n_obreros_eventuales_mujeres',
        'n_propietarios_hombres',
        'n_propietarios_mujeres',
        'n_familiares_no_remunerados_hombres',
        'n_familiares_no_remunerados_mujeres',
        'n_practicantes_hombres',
        'n_practicantes_mujeres',
        'n_personal_servicios_honorarios_hombres',
        'n_personal_servicios_honorarios_mujeres',
        'n_comisionistas_hombres',
        'n_comisionistas_mujeres',
        'n_trabajadores_postgrado',
        'n_trabajadores_universitaria_completa',
        'n_trabajadores_universitaria_incompleta',
        'n_trabajadores_tecnico_completa',
        'n_trabajadores_tecnico_incompleta',
        'n_trabajadores_secundaria_primaria',
        'n_trabajadores_inicial_sin_nivel'
      ]

      for column in expanded_columns:
        df[column] = df[column] * df['factor_expansion']

      return df

class EncuestaEmpresasPipeline(EasyPipeline):
    @staticmethod
    def steps(params):

        db_connector = Connector.fetch('clickhouse-database', open('../conns.yaml'))

        dtypes = {
          # 01_EMPRESA_IDENTIFICA
          'company_id':                'UInt32', 
          'district_id':               'String', 
          # 'ruc':                       'Float32', 
          # 'razon_social':              'Float32', 
          # 'nombre_comercial':          'Float32',
          'anio_inicio_actividades':   'UInt32', 
          'ciiu_rev4':                 'String', 
          'ciiu_rev4_a':               'String', 
          'ciiu_rev4_b':               'String',
          # 'ciiu_rev4_c':               'String', 
          # 'ciiu_rev4_d':               'String', 
          'tipo_sociedad':             'UInt8', 
          # 'tipo_sociedad_text':        'String',
          'rango_ventas_2014':         'UInt8', 
          'factor_expansion':          'Float64',

          # 02_MÓDULO_I_II_III_1
          # 'plan_negocios':                                        'UInt8', 
          # 'credito_inicio_operaciones':                           'UInt8',
          'institucion_credito':                                  'UInt8', 
          'areas_funcionales_identificar':                        'UInt8',
          'recursos_humanos':                                     'UInt8', 
          'logistica_aprovisionamiento':                          'UInt8', 
          'comercializacion':                                     'UInt8',
          'contabilidad':                                         'UInt8', 
          'produccion':                                           'UInt8', 
          'direccion_gerencia':                                   'UInt8', 
          'area_legal':                                           'UInt8',
          'soporte_informatico':                                  'UInt8', 
          'otro':                                                 'UInt8', 
          'participa_mercado_internacional':                      'UInt8',
          'participa_mercado_nacional':                           'UInt8', 
          'participa_mercado_local':                              'UInt8',
          'mercado_principal':                                    'UInt8', 
          # 'considera_competencia_existe':                         'UInt8',
          'competencia_informal_precio':                          'UInt8', 
          'competencia_informal_calidad':                         'UInt8',
          'competencia_informal_grado_diferenciacion':            'UInt8',
          'competencia_informal_tiempo_entrega':                  'UInt8',
          'competencia_informal_promociones_descuentos':          'UInt8',
          'competencia_informal_servicio_cliente':                'UInt8', 
          'competencia_informal_otro':                            'UInt8',
          # 'pertenece_organizacion_fin_empresarial':               'UInt8',
          # 'anio_incorporacion_organizacion_fin_empresarial':      'UInt32',
          # 'tipo_organizacion_fin_empresarial':                    'UInt8', 
          # 'acceso_info_negociar_proveedores':                     'UInt8',
          # 'acceso_info_servicios_financieros':                    'UInt8', 
          # 'acceso_info_acceso_mercados':                          'UInt8',
          # 'acceso_info_empresarial':                              'UInt8', 
          # 'acceso_capacitacion_asis_tecnica':                     'UInt8',
          # 'acceso_info_vigilancia_limpieza':                      'UInt8', 
          # 'acceso_info_infraestructura':                          'UInt8',
          # 'acceso_info_otro':                                     'UInt8', 
          'utilidad_relacion_asociatividad_2014':                 'UInt8',
          # 'no_pertenece_organizacion_agrupacion':                 'UInt8', 
          'local_electricidad_publica':                           'UInt8',
          # 'interrupciones_electricas_programadas':                'UInt8',
          # 'interrupciones_electricas_no_programadas':             'UInt8',
          # 'dispo_servicio_electrico_horas_dias':                  'UInt8',
          # 'demora_no_atienden_reclamos_servicio_electrico':       'UInt8',
          # 'costo_elevado_servicio_electrico':                     'UInt8',
          # 'intensidad_corriente_electrica_variable':              'UInt8',
          # 'errores_facturacion_servicio_electrico':               'UInt8',
          # 'otro_problema_servicio_electrico':                     'UInt8',
          # 'otro_problema_servicio_electrico_nombre':              'String',
          # 'no_problema_servicio_electrico':                       'UInt8', 
          'cuenta_agua_red_publica':                              'UInt8',
          # 'interrupciones_suministro_agua_programadas':           'UInt8',
          # 'interrupciones_suministro_agua_no_programadas':        'UInt8',
          # 'dispo_suministro_agua_horas_dias':                     'UInt8',
          # 'demora_no_atienden_reclamos_suministro_agua':          'UInt8',
          # 'costo_elevado_suministro_agua':                        'UInt8', 
          # 'intensidad_suministro_agua_variable':                  'UInt8',
          # 'errores_facturacion_servicio_agua':                    'UInt8', 
          # 'mala_calidad_agua':                                    'UInt8',
          # 'otro_problema_servicio_suministro_agua':               'UInt8', 
          # 'tiene_ejecutivos':                                     'UInt8',
          # 'n_ejecutivos_total':                                   'UInt16', 
          'n_ejecutivos_hombres':                                 'Float32', 
          'n_ejecutivos_mujeres':                                 'Float32',
          'ejecutivos_remuneracion_promedio_mensual':             'Float32',
          # 'tiene_empleados_permanentes':                          'UInt8', 
          # 'n_empleados_permanentes_total':                        'UInt16',
          'n_empleados_permanentes_hombres':                      'Float32', 
          'n_empleados_permanentes_mujeres':                      'Float32',
          'empleados_permanentes_remuneracion_promedio_mensual':  'Float32',
          # 'tiene_obreros_permanentes':                            'UInt8', 
          # 'n_obreros_permanentes_total':                          'UInt16',
          'n_obreros_permanentes_hombres':                        'Float32', 
          'n_obreros_permanentes_mujeres':                        'Float32',
          'obreros_permanentes_remuneracion_promedio_mensual':    'Float32',
          # 'tiene_empleados_eventuales':                           'UInt8', 
          # 'n_empleados_eventuales_total':                         'UInt16',
          'n_empleados_eventuales_hombres':                       'Float32', 
          'n_empleados_eventuales_mujeres':                       'Float32',
          'empleados_eventuales_remuneracion_promedio_mensual':   'Float32',
          # 'tiene_obreros_eventuales':                             'UInt8', 
          # 'n_obreros_eventuales_total':                           'UInt16',
          'n_obreros_eventuales_hombres':                         'Float32', 
          'n_obreros_eventuales_mujeres':                         'Float32',
          'obreros_eventuales_remuneracion_promedio_mensual':     'Float32',
          # 'tiene_total_1_2_3_4_5':                                'UInt8', 
          # 'n_total_1_2_3_4_5_total':                              'Float32',
          # 'n_total_1_2_3_4_5_hombres':                            'UInt16', 
          # 'n_total_1_2_3_4_5_mujeres':                            'UInt16',
          # 'tiene_propietarios':                                   'UInt8', 
          # 'n_propietarios_total':                                 'UInt16', 
          'n_propietarios_hombres':                               'Float32',
          'n_propietarios_mujeres':                               'Float32',

          # 02_MÓDULO_I_II_III_2
          # 'tiene_familiares_no_remunerados':                              'UInt8',
          # 'n_familiares_no_remunerados_total':                            'UInt16',
          'n_familiares_no_remunerados_hombres':                          'Float32',
          'n_familiares_no_remunerados_mujeres':                          'Float32', 
          # 'tiene_practicantes':                                           'UInt8',
          # 'n_practicantes_total':                                         'UInt16', 
          'n_practicantes_hombres':                                       'Float32',
          'n_practicantes_mujeres':                                       'Float32', 
          # 'tiene_personal_servicios_honorarios':                          'UInt8',
          # 'n_personal_servicios_honorarios_total':                        'UInt16',
          'n_personal_servicios_honorarios_hombres':                      'Float32',
          'n_personal_servicios_honorarios_mujeres':                      'Float32', 
          # 'tiene_comisionistas':                                          'UInt8',
          # 'n_comisionistas_total':                                        'UInt16', 
          'n_comisionistas_hombres':                                      'Float32',
          'n_comisionistas_mujeres':                                      'Float32', 
          # 'tiene_total_7_8_9_10_11':                                      'UInt8',
          # 'n_total_7_8_9_10_11_total':                                    'UInt16', 
          # 'n_total_7_8_9_10_11_hombres':                                  'UInt16',
          # 'n_total_7_8_9_10_11_mujeres':                                  'UInt16',
          # 'tiene_personal_servicios_intermediacion':                      'UInt8',
          # 'n_personal_servicios_intermediacion_total':                    'UInt16',
          # 'n_personal_servicios_intermediacion_hombres':                  'UInt16',
          # 'n_personal_servicios_intermediacion_mujeres':                  'UInt16',
          'n_trabajadores_postgrado':                                     'Float64', 
          'n_trabajadores_universitaria_completa':                        'Float64',
          'n_trabajadores_universitaria_incompleta':                      'Float64',
          'n_trabajadores_tecnico_completa':                              'Float64', 
          'n_trabajadores_tecnico_incompleta':                            'Float64',
          'n_trabajadores_secundaria_primaria':                           'Float64',
          'n_trabajadores_inicial_sin_nivel':                             'Float64', 
          # 'n_nivel_estudios_total':                                       'UInt16',
          'conoce_modalidad_teletrabajo':                                 'UInt8', 
          'teletrabajo_adecuado_empresa':                                 'UInt8',
          # 'entrega_incentivos_trabajadores_buenos_resultados':            'UInt8',
          # 'entrega_incentivos_economicos':                                'UInt8', 
          # 'otorga_ascensos':                                              'UInt8',
          # 'otorga_capacitaciones':                                        'UInt8', 
          # 'otorga_viajes':                                                'UInt8', 
          # 'otorga_otro_incentivo':                                        'UInt8',
          'requiere_contratar_personal_2014':                             'UInt8',
          'contratar_personal_innovacion_teconologica':                   'UInt8',
          'contratar_personal_estacionalidad':                            'UInt8',
          'contratar_personal_renuncia_personal':                         'UInt8',
          'contratar_personal_nueva_linea_negocio':                       'UInt8',
          'contratar_personal_expansion_empresa':                         'UInt8', 
          'contratar_personal_jubilacion':                                'UInt8',
          'contratar_personal_otro':                                      'UInt8', 
          # 'dificultad_contratar_trabajadores_2014':                       'UInt8',
          'dificultad_contratar_escasez_postulante':                      'UInt8',
          'dificultad_contratar_formacion_academica':                     'UInt8',
          'dificultad_contratar_experiencia':                             'UInt8',
          'dificultad_contratar_habilidades_personales_deseadas':         'UInt8',
          'dificultad_contratar_informacion_confiable_postulante':        'UInt8',
          'dificultad_contratar_periodo_contrato':                        'UInt8',
          'dificultad_contratar_remuneraciones':                          'UInt8',
          'dificultad_contratar_destino_geografico':                      'UInt8',
          'dificultad_contratar_jornada_laboral':                         'UInt8',
          'dificultad_contratar_busqueda_postulantes':                    'UInt8',
          'dificultad_contratar_otro':                                    'UInt8', 
          # 'dificil_conseguir_directivo_general':                          'UInt8',
          # 'dificil_conseguir_profesionales':                              'UInt8', 
          # 'dificil_conseguir_tecnicos':                                   'UInt8',
          # 'dificil_conseguir_operarios_calificados':                      'UInt8',
          # 'dificil_conseguir_operarios_no_calificados':                   'UInt8',
          # 'trabajadores_capacitacion_2014':                               'UInt8',
          # 'brinda_capacitacion_centros_formacion_sectoriales':            'UInt8',
          # 'brinda_capacitacion_universidad_instituto_publico':            'UInt8',
          # 'brinda_capacitacion_universidad_instituto_privado':            'UInt8',
          # 'brinda_capacitacion_institucion_publica':                      'UInt8',
          # 'brinda_capacitacion_centro_innovacion_tecnologica':            'UInt8',
          # 'brinda_capacitacion_camara_comercio':                          'UInt8',
          # 'brinda_capacitacion_proveedores_empresa':                      'UInt8',
          # 'brinda_capacitacion_propia_empresa_casa_matriz':               'UInt8',
          # 'brinda_capacitacion_instructor_externo':                       'UInt8', 
          # 'brinda_capacitacion_otro':                                     'UInt8',
          # 'n_trabajadores_capacitaciones_idiomas':                        'UInt16',
          # 'n_trabajadores_capacitaciones_gestion_empresarial':            'UInt16',
          # 'n_trabajadores_capacitaciones_seguridad_salud_ocupacional':    'UInt16',
          # 'n_trabajadores_capacitaciones_tic':                            'UInt16',
          # 'n_trabajadores_capacitaciones_habilidades_socio_emocionales':  'UInt16',
          # 'n_trabajadores_capacitaciones_temas_tecnicos_productivos':     'UInt16',
          # 'n_trabajadores_capacitaciones_marketing':                      'UInt16',
          # 'n_trabajadores_capacitaciones_otro':                           'UInt16', 
          # 'razon_no_realiza_capacitaciones':                              'UInt8',
          # 'conoce_credito_beneficio_tributario_gastos_capacitacion':      'UInt8',
          # 'utiliza_utilizaria_dicho_credito':                             'UInt8',          

          # 03_MÓDULO_IV_1
          # 'modalidad_realizar_compras_2014':                                'UInt8',
          # 'publicidad_conoce_proveedores':                                  'UInt8', 
          # 'pedido_proveedor_internacional_2014':                            'UInt8',
          # 'razon_pedido_insumos_proveedor_internacional_2014':              'UInt8',
          # 'razon_no_realiza_compras_proveedor_internacional':               'UInt8',
          # 'realiza_compras_internet_empresa_2014':                          'UInt8',
          # 'portentaje_total_compras_internet':                              'Float32', 
          # 'frecuencia_compras_internet_2014':                               'UInt8',
          # 'medio_pago_compras_internet_tarjeta_credito':                    'UInt8',
          # 'medio_pago_compras_internet_transferencia':                      'UInt8',
          # 'medio_pago_compras_internet_billetera_electronica':              'UInt8',
          # 'medio_pago_compras_internet_contra_entrega_terminal_de_pago':    'UInt8',
          # 'medio_pago_compras_internet_otro':                               'UInt8',
          # 'tecnologia_predominante_proceso_produccion':                     'UInt8',
          # 'fuente_energia_utiliza_electricidad':                            'UInt8', 
          # 'fuente_energia_utiliza_diesel':                                  'UInt8',
          # 'fuente_energia_utiliza_carbon':                                  'UInt8', 
          # 'fuente_energia_utiliza_gas_natural':                             'UInt8',
          # 'fuente_energia_utiliza_gas_licuado':                             'UInt8', 
          # 'fuente_energia_utiliza_otro':                                    'UInt8',
          # 'porcentaje_utiliza_capacidad_instalada_2014':                    'Float32', 
          # 'modalidad_venta_2014':                                           'UInt8',
          # 'realiza_estudios_mercado_para_promocion_producto_servicio_2014': 'UInt8',
          # 'realiza_ventas_internet_2014':                                   'UInt8', 
          # 'porcentaje_ventas_internet_2014':                                'Float32',

          # 03_MÓDULO_IV_2
          # 'realiza_ventas_internet_exterior_2014':                  'UInt8',
          # 'contrato_servicios_asesoria_juridica':                   'UInt8',
          # 'contrato_servicios_asesoria_economica_financiera':       'UInt8',
          # 'contrato_servicios_auditoria_contable_financiera':       'UInt8',
          # 'contrato_servicios_contabilidad_asesoria_contable':      'UInt8',
          # 'contrato_servicios_soporte_informatico':                 'UInt8',
          # 'contrato_servicios_mensajeria':                          'UInt8',
          # 'contrato_servicios_alquiler_maquinaria_mantenimiento':   'UInt8',
          # 'contrato_servicios_limpieza':                            'UInt8', 
          # 'contrato_servicios_cobro_clientes':                      'UInt8',
          # 'contrato_servicios_asistencia_temas_ambientales':        'UInt8',
          # 'contrato_servicios_tramites_aduana':                     'UInt8',
          # 'contrato_servicios_etiquetado_empaquetado_embalaje':     'UInt8',
          # 'contrato_servicios_marketing':                           'UInt8', 
          # 'contrato_servicios_seguridad':                           'UInt8',
          # 'contrato_servicios_otro':                                'UInt8', 
          # 'contrato_servicios_otro_respuesta_abierta':              'String',

          # 04_MÓDULO_V_VI_1
          # 'dispone_computadora_escritorio':                                         'UInt8',
          # 'cantidad_computadora_escritorio':                                        'UInt16', 
          # 'antiguedad_computadora_escritorio':                                      'UInt8',
          # 'dispone_computadora_portatil':                                           'UInt8', 
          # 'cantidad_computadora_portatil':                                          'UInt16',
          # 'antiguedad_computadora_portatil':                                        'UInt8', 
          # 'dispone_multifuncional':                                                 'UInt8',
          # 'cantidad_multifuncional':                                                'UInt16',
          # 'antiguedad_multifuncional':                                              'UInt8',
          # 'dispone_impresora':                                                      'UInt8', 
          # 'cantidad_impresora':                                                     'UInt16', 
          # 'antiguedad_impresora':                                                   'UInt8',
          # 'dispone_escaner':                                                        'UInt8', 
          # 'cantidad_escaner':                                                       'UInt16', 
          # 'antiguedad_escaner':                                                     'UInt8',
          # 'dispone_smartphone':                                                     'UInt8', 
          # 'cantidad_smartphone':                                                    'UInt16', 
          # 'antiguedad_smartphone':                                                  'UInt8',
          # 'otro_dispone':                                                           'UInt8', 
          # 'otro_dispone_especifique':                                               'String', 
          # 'cantidad_otro_dispone':                                                  'UInt16',
          # 'antiguedad_otro_dispone':                                                'UInt8', 
          # 'utiliza_pagina_web':                                                     'UInt8',
          # 'utiliza_redes_sociales':                                                 'UInt8', 
          # 'utiliza_linkedin':                                                       'UInt8', 
          # 'tiene_software_contable':                                                'UInt8',
          # 'tiene_software_ventas':                                                  'UInt8', 
          # 'tiene_software_personal':                                                'UInt8',
          # 'tiene_software_finanzas':                                                'UInt8', 
          # 'tiene_software_logistica':                                               'UInt8',
          # 'tiene_software_produccion':                                              'UInt8', 
          # 'tiene_software_soporte_informatico':                                     'UInt8',
          # 'tiene_software_otro':                                                    'UInt8', 
          # 'tiene_software_otro_especifique':                                        'String',
          # 'tiene_software_ninguno':                                                 'UInt8',
          # 'porcentaje_trabajadores_utiliza_computadoras':                           'Float32',
          # 'porcentaje_trabajadores_utiliza_servicio_internet':                      'Float32',
          # 'utiliza_internet_para_busqueda_productos_servicios':                     'UInt8',
          # 'utiliza_internet_para_busqueda_organismos_gubernamentales':              'UInt8',
          # 'utiliza_internet_para_busqueda_informacion_investigacion_desarrollo':    'UInt8',
          # 'utiliza_internet_para_otra_busqueda_informacion':                        'UInt8',
          # 'utiliza_internet_para_comunicaciones':                                   'UInt8',
          # 'utiliza_internet_para_operaciones_banca_elecctronica':                   'UInt8',
          # 'utiliza_internet_para_tramites_organismos_gubernamentales':              'UInt8',
          # 'utiliza_internet_para_servicio_soporte_cliente':                         'UInt8',
          # 'utiliza_internet_para_ventas_bienes_servicios':                          'UInt8',
          # 'utiliza_internet_para_promocionar_productos_servicios':                  'UInt8',
          # 'utiliza_internet_para_capacitacion_personal':                            'UInt8',
          # 'utiliza_internet_para_video_conferencia':                                'UInt8',
          # 'utiliza_internet_para_emision_facturas_electronicas':                    'UInt8',
          # 'utiliza_internet_para_servicios_computacion_nube':                       'UInt8',
          # 'utiliza_internet_otro':                                                  'UInt8',
          # 'razon_no_servicio_internet_no_necesita_no_utilidad_empresa':             'UInt8',
          # 'razon_no_servicio_internet_desconoce_usarlo':                            'UInt8',
          # 'razon_no_servicio_internet_no_rentable_caro':                            'UInt8',
          # 'razon_no_servicio_internet_no_seguro':                                   'UInt8',
          # 'razon_no_servicio_internet_otro':                                        'UInt8',
          # 'razon_no_dispone_computadoras_no_necesita_no_utilidad_empresa':          'UInt8',
          # 'razon_no_dispone_computadoras_desconoce_usarlo':                         'UInt8',
          # 'razon_no_dispone_computadoras_no_rentable_caro':                         'UInt8',
          # 'razon_no_dispone_computadoras_otro':                                     'UInt8',
          # 'empresa_dispuso_telefonos_moviles':                                      'UInt8',

          # 04_MÓDULO_V_VI_2
          # 'utiliza_servicio_correo_postal_2014':                              'UInt8',
          'realiza_exportaciones_2014':                                       'UInt8',
          'dificultad_exportar_falta_informacion_procesos':                   'UInt8',
          'dificultad_exportar_costos_logisticos':                            'UInt8',
          'dificultad_exportar_identificacion_mercados_compradores':          'UInt8',
          'dificultad_exportar_acceso_financiamiento_operaciones':            'UInt8',
          'dificultad_exportar_cumplir_normas_requisitos_calidad':            'UInt8',
          'dificultad_exportar_cumplir_requisitos_cantidad_compradores':      'UInt8',
          'dificultad_exportar_retrasos_causados_transporte':                 'UInt8',
          'dificultad_exportar_procedimientos_aduaneros':                     'UInt8',
          'dificultad_exportar_retrasos_aduana':                              'UInt8',
          'dificultad_exportar_barreras_arancelarias_extranjero':             'UInt8',
          'dificultad_exportar_corrupcion_fronteras':                         'UInt8',
          'dificultad_exportar_ninguna':                                      'UInt8',

          # 05_MÓDULO_VII_VIII_IX
          'criterio_elegir_credito_prestamo_tasas_interes':                                               'UInt8',
          'criterio_elegir_credito_prestamo_plazo_pago':                                                  'UInt8',
          'criterio_elegir_credito_prestamo_garantias_solicitadas':                                       'UInt8',
          'criterio_elegir_credito_prestamo_prestigio_entidad_financiera':                                'UInt8',
          'criterio_elegir_credito_prestamo_recomendacion_terceros':                                      'UInt8',
          'criterio_elegir_credito_prestamo_beneficios_entidad':                                          'UInt8',
          'criterio_elegir_credito_prestamo_rapidez_otorgamiento':                                        'UInt8',
          'criterio_elegir_credito_prestamo_periodo_gracia':                                             'UInt8',
          'criterio_elegir_credito_prestamo_otro':                                                        'UInt8',
          # 'duracion_contrato_trabajadores_2014':                                                          'UInt8',
          # 'califica_requisitos_mtpe_contratacion_trabajadores_plazo_fijo':                                'UInt8',
          # 'n_trabajadores_promedio_plazo_indeterminado':                                                  'UInt16',
          # 'califica_requisitos_mtpe_contratacion_trabajadores_plazo_indeterminado':                       'UInt8',
          # 'conocimiento_minimo_requerido_trabajadores_discapacidad_contratar':                            'UInt8',
          # 'califica_porcentaje_contratacion_personas_discapacidad':                                       'UInt8',
          # 'califica_exigencias_infraestructura_personas_discapacidad':                                    'UInt8',
          # 'califica_cumplimiento_empresas_obligaciones_seguridad_salud':                                  'UInt8',
          # 'califica_requisitos_tercerizacion_laboral_empresas':                                           'UInt8',
          # 'afecta_decision_contratar_pago_beneficios_sociales_tercerizacion_laboral':                     'UInt8',
          # 'califica_cumplimiento_obligaciones_proteccion_maternidad':                                     'UInt8',
          # 'conoce_sunafil':                                                                               'UInt8',
          # 'califica_labor_fiscalizacion_regulacion_laboral_sunafil':                                      'UInt8',
          # 'cuenta_instrumentos_gestion_ambiental':                                                        'UInt8',
          # 'motivo_aplicar_instrumentos_gestion_ambiental_su_rubro':                                       'UInt8',
          # 'motivo_aplicar_instrumentos_gestion_ambiental_su_rubro_respuesta_abierta':                     'String',
          # 'califica_procedimientos_obtencion_declaracion_impacto_ambiental':                              'UInt8',
          # 'califica_procedimientos_obtencion_estudio_impacto_ambiental':                                  'UInt8',
          # 'califica_procedimientos_obtencion_declaracion_ambiental_actividades_curso':                    'UInt8',
          # 'califica_procedimientos_obtencion_programa_adecuacion_manejo_ambiental':                       'UInt8',
          # 'califica_actividades_fiscalizacion_sancion_materia_regulacion_ambiental_2014':                 'UInt8',
          # 'califica_actividades_fiscalizacion_sancion_materia_regulacion_ambiental_oefa':                 'UInt8',
          # 'califica_actividades_fiscalizacion_sancion_materia_regulacion_ambiental_osinfor':              'UInt8',
          # 'califica_actividades_fiscalizacion_sancion_materia_regulacion_ambiental_gobierno_regional':    'UInt8',
          # 'regimen_tributario_empresa_2014':                                                              'UInt8',
          # 'regimen_tributario_empresa_2014_respuesta_abierta':                                            'String',
          # 'califica_procedimientos_obligacion_impuestos_nacionales':                                      'UInt8',
          # 'califica_procedimientos_pago_tributo_municipal':                                               'UInt8',
          # 'califica_actividades_fiscalizacion_sancion_materia_tributos_nacionales_2014':                  'UInt8',
          # 'califica_actividades_fiscalizacion_sancion_materia_tributos_municipalidad_jurisdiccion_2014':  'UInt8',
          # 'dias_demora_obtener_licencia_funcionamiento':                                                  'UInt8',
          # 'califica_procedimientos_obtencion_licencia_funcionamimento':                                   'UInt8',
          # 'ha_solicitado_autorizacion_sectorial':                                                         'UInt8',
          # 'califica_procedimientos_obtencion_autorizacion_sectorial':                                     'UInt8',
          # 'requerimientos_diferente_permiso_sectorial_pago':                                              'UInt8',
          # 'obtuvo_certificado_seguridad_defensa_civil':                                                   'UInt8',
          # 'dias_demora_obtener_certificado_seguridad_defensa_civil':                                      'UInt8',
          # 'tipo_certificado_seguridad_defensa_civil':                                                     'UInt8',
          # 'califica_procedimiento_obtener_certificado_seguridad_defensa_civil':                           'UInt8',
          # 'empresa_atendio_inspeccion_tecnicas_seguridad_defensa_civil':                                  'UInt8',
          # 'factor_limita_crecimiento_empresa_financiamiento':                                             'UInt8',
          # 'factor_limita_crecimiento_empresa_proceso_productivo_poco_automatizado':                       'UInt8',
          # 'factor_limita_crecimiento_empresa_falta_mano_obra_calificada':                                 'UInt8',
          # 'factor_limita_crecimiento_empresa_falta_repuesto_servicio_tecnico_maquinaria':                 'UInt8',
          # 'factor_limita_crecimiento_empresa_demanda_limitada':                                           'UInt8',
          # 'factor_limita_crecimiento_empresa_falta_insumos_nacionales':                                   'UInt8',
          # 'factor_limita_crecimiento_empresa_falta_insumos_importados':                                   'UInt8',
          # 'factor_limita_crecimiento_empresa_falta_energia_electrica':                                    'UInt8',
          # 'factor_limita_crecimiento_empresa_falta_informacion_tecnologica':                              'UInt8',
          # 'factor_limita_crecimiento_empresa_falta_informacion_mercados':                                 'UInt8',
          # 'factor_limita_crecimiento_empresa_excesiva_regulacion_laboral':                                'UInt8',
          # 'factor_limita_crecimiento_empresa_excesiva_regulacion_tributaria':                             'UInt8',
          # 'factor_limita_crecimiento_empresa_excesiva_regulacion_ambiental':                              'UInt8',
          # 'factor_limita_crecimiento_empresa_excesiva_regulacion_licencia_funcionamiento_construccion':   'UInt8',
          # 'factor_limita_crecimiento_empresa_excesiva_regulacion_defensa_civil':                          'UInt8',
          # 'factor_limita_crecimiento_empresa_excesiva_regulacion_tramites_sectoriales_autorizaciones':    'UInt8',
          # 'factor_limita_crecimiento_empresa_corrupcion_funcionarios_publicos':                           'UInt8',
          # 'factor_limita_crecimiento_empresa_contrabando':                                                'UInt8',
          # 'factor_limita_crecimiento_empresa_exceso_cargas_tributarias':                                  'UInt8',
          # 'factor_limita_crecimiento_empresa_informalidad':                                               'UInt8',
          # 'factor_limita_crecimiento_empresa_otro':                                                       'UInt8',
          # 'factor_limita_crecimiento_empresa_ninguno':                                                    'UInt8'
        }

        transform_step_01 = Module1Step()
        transform_step_02_01 = Module21Step()
        transform_step_02_02 = Module22Step()
        # transform_step_03_01 = Module31Step()
        # transform_step_03_02 = Module32Step()
        # transform_step_04_01 = Module41Step()
        transform_step_04_02 = Module42Step()
        transform_step_05 = Module5Step()
        join_step = JoinStep()
        load_step = LoadStep(
          'inei_ene', connector=db_connector, if_exists='drop',
          pk=['district_id', 'company_id', 'year'], dtype=dtypes, nullable_list=[
            # 01_EMPRESA_IDENTIFICA
            # 'ruc', 
            # 'razon_social', 
            # 'nombre_comercial',
            'anio_inicio_actividades', 
            'ciiu_rev4', 
            'ciiu_rev4_a', 
            'ciiu_rev4_b',
            # 'ciiu_rev4_c', 
            # 'ciiu_rev4_d', 
            'tipo_sociedad', 
            # 'tipo_sociedad_text',
            'rango_ventas_2014', 
            'factor_expansion',

            # 02_MÓDULO_I_II_III_1
            # 'plan_negocios', 'credito_inicio_operaciones',
            'institucion_credito', 
            'areas_funcionales_identificar',
            'recursos_humanos', 'logistica_aprovisionamiento', 'comercializacion',
            'contabilidad', 'produccion', 'direccion_gerencia', 'area_legal',
            'soporte_informatico', 'otro', 'participa_mercado_internacional',
            'participa_mercado_nacional', 'participa_mercado_local',
            'mercado_principal', 
            # 'considera_competencia_existe',
            'competencia_informal_precio', 'competencia_informal_calidad',
            'competencia_informal_grado_diferenciacion',
            'competencia_informal_tiempo_entrega',
            'competencia_informal_promociones_descuentos',
            'competencia_informal_servicio_cliente', 'competencia_informal_otro',
            # 'pertenece_organizacion_fin_empresarial',
            # 'anio_incorporacion_organizacion_fin_empresarial',
            # 'tipo_organizacion_fin_empresarial', 'acceso_info_negociar_proveedores',
            # 'acceso_info_servicios_financieros', 'acceso_info_acceso_mercados',
            # 'acceso_info_empresarial', 'acceso_capacitacion_asis_tecnica',
             #'acceso_info_vigilancia_limpieza', 'acceso_info_infraestructura',
            # 'acceso_info_otro', 
            'utilidad_relacion_asociatividad_2014',
            #'no_pertenece_organizacion_agrupacion', 
            'local_electricidad_publica',
            # 'interrupciones_electricas_programadas',
            # 'interrupciones_electricas_no_programadas',
            # 'dispo_servicio_electrico_horas_dias',
            # 'demora_no_atienden_reclamos_servicio_electrico',
            # 'costo_elevado_servicio_electrico',
            # 'intensidad_corriente_electrica_variable',
            # 'errores_facturacion_servicio_electrico',
            # 'otro_problema_servicio_electrico',
            # 'otro_problema_servicio_electrico_nombre',
            # 'no_problema_servicio_electrico', 
            'cuenta_agua_red_publica',
            # 'interrupciones_suministro_agua_programadas',
            # 'interrupciones_suministro_agua_no_programadas',
            # 'dispo_suministro_agua_horas_dias',
            #'demora_no_atienden_reclamos_suministro_agua',
            #'costo_elevado_suministro_agua', 'intensidad_suministro_agua_variable',
            # 'errores_facturacion_servicio_agua', 'mala_calidad_agua',
            # 'otro_problema_servicio_suministro_agua', 'tiene_ejecutivos',
            # 'n_ejecutivos_total', 
            'n_ejecutivos_hombres', 'n_ejecutivos_mujeres',
            'ejecutivos_remuneracion_promedio_mensual',
            # 'tiene_empleados_permanentes', 'n_empleados_permanentes_total',
            'n_empleados_permanentes_hombres', 'n_empleados_permanentes_mujeres',
            'empleados_permanentes_remuneracion_promedio_mensual',
            # 'tiene_obreros_permanentes', 'n_obreros_permanentes_total',
            'n_obreros_permanentes_hombres', 'n_obreros_permanentes_mujeres',
            'obreros_permanentes_remuneracion_promedio_mensual',
            # 'tiene_empleados_eventuales', 'n_empleados_eventuales_total',
            'n_empleados_eventuales_hombres', 'n_empleados_eventuales_mujeres',
            'empleados_eventuales_remuneracion_promedio_mensual',
            # 'tiene_obreros_eventuales', 'n_obreros_eventuales_total',
            'n_obreros_eventuales_hombres', 'n_obreros_eventuales_mujeres',
            'obreros_eventuales_remuneracion_promedio_mensual',
            # 'tiene_total_1_2_3_4_5', 'n_total_1_2_3_4_5_total',
            # 'n_total_1_2_3_4_5_hombres', 'n_total_1_2_3_4_5_mujeres',
            # 'tiene_propietarios', 'n_propietarios_total', 
            'n_propietarios_hombres',
            'n_propietarios_mujeres',

            # 02_MÓDULO_I_II_III_2
            # 'tiene_familiares_no_remunerados',
            # 'n_familiares_no_remunerados_total',
            'n_familiares_no_remunerados_hombres',
            'n_familiares_no_remunerados_mujeres', 
            # 'tiene_practicantes',
            # 'n_practicantes_total', 
            'n_practicantes_hombres',
            'n_practicantes_mujeres', 
            #'tiene_personal_servicios_honorarios',
            #'n_personal_servicios_honorarios_total',
            'n_personal_servicios_honorarios_hombres',
            'n_personal_servicios_honorarios_mujeres', 
            #'tiene_comisionistas',
            #'n_comisionistas_total', 
            'n_comisionistas_hombres',
            'n_comisionistas_mujeres', 
            # 'tiene_total_7_8_9_10_11',
            # 'n_total_7_8_9_10_11_total', 'n_total_7_8_9_10_11_hombres',
            # 'n_total_7_8_9_10_11_mujeres',
            # 'tiene_personal_servicios_intermediacion',
            # 'n_personal_servicios_intermediacion_total',
            # 'n_personal_servicios_intermediacion_hombres',
            # 'n_personal_servicios_intermediacion_mujeres',
            'n_trabajadores_postgrado', 'n_trabajadores_universitaria_completa',
            'n_trabajadores_universitaria_incompleta',
            'n_trabajadores_tecnico_completa', 'n_trabajadores_tecnico_incompleta',
            'n_trabajadores_secundaria_primaria',
            'n_trabajadores_inicial_sin_nivel',
            # 'n_nivel_estudios_total',
            'conoce_modalidad_teletrabajo', 'teletrabajo_adecuado_empresa',
            # 'entrega_incentivos_trabajadores_buenos_resultados',
            # 'entrega_incentivos_economicos', 'otorga_ascensos',
            # 'otorga_capacitaciones', 'otorga_viajes', 'otorga_otro_incentivo',
            'requiere_contratar_personal_2014',
            'contratar_personal_innovacion_teconologica',
            'contratar_personal_estacionalidad',
            'contratar_personal_renuncia_personal',
            'contratar_personal_nueva_linea_negocio',
            'contratar_personal_expansion_empresa', 'contratar_personal_jubilacion',
            'contratar_personal_otro', 
            # 'dificultad_contratar_trabajadores_2014',
            'dificultad_contratar_escasez_postulante',
            'dificultad_contratar_formacion_academica',
            'dificultad_contratar_experiencia',
            'dificultad_contratar_habilidades_personales_deseadas',
            'dificultad_contratar_informacion_confiable_postulante',
            'dificultad_contratar_periodo_contrato',
            'dificultad_contratar_remuneraciones',
            'dificultad_contratar_destino_geografico',
            'dificultad_contratar_jornada_laboral',
            'dificultad_contratar_busqueda_postulantes',
            'dificultad_contratar_otro', 
            # 'dificil_conseguir_directivo_general',
            #'dificil_conseguir_profesionales', 'dificil_conseguir_tecnicos',
            #'dificil_conseguir_operarios_calificados',
            #'dificil_conseguir_operarios_no_calificados',
            #'trabajadores_capacitacion_2014',
            #'brinda_capacitacion_centros_formacion_sectoriales',
            #'brinda_capacitacion_universidad_instituto_publico',
            #'brinda_capacitacion_universidad_instituto_privado',
            #'brinda_capacitacion_institucion_publica',
            #'brinda_capacitacion_centro_innovacion_tecnologica',
            #'brinda_capacitacion_camara_comercio',
            #'brinda_capacitacion_proveedores_empresa',
            #'brinda_capacitacion_propia_empresa_casa_matriz',
            #'brinda_capacitacion_instructor_externo', 'brinda_capacitacion_otro',
            #'n_trabajadores_capacitaciones_idiomas',
            #'n_trabajadores_capacitaciones_gestion_empresarial',
            #'n_trabajadores_capacitaciones_seguridad_salud_ocupacional',
            #'n_trabajadores_capacitaciones_tic',
            #'n_trabajadores_capacitaciones_habilidades_socio_emocionales',
            #'n_trabajadores_capacitaciones_temas_tecnicos_productivos',
            #'n_trabajadores_capacitaciones_marketing',
            #'n_trabajadores_capacitaciones_otro', 'razon_no_realiza_capacitaciones',
            #'conoce_credito_beneficio_tributario_gastos_capacitacion',
            #'utiliza_utilizaria_dicho_credito',

            # 03_MÓDULO_IV_1
            # 'modalidad_realizar_compras_2014',
            # 'publicidad_conoce_proveedores', 'pedido_proveedor_internacional_2014',
            # 'razon_pedido_insumos_proveedor_internacional_2014',
            # 'razon_no_realiza_compras_proveedor_internacional',
            # 'realiza_compras_internet_empresa_2014',
            # 'portentaje_total_compras_internet', 'frecuencia_compras_internet_2014',
            # 'medio_pago_compras_internet_tarjeta_credito',
            # 'medio_pago_compras_internet_transferencia',
            # 'medio_pago_compras_internet_billetera_electronica',
            # 'medio_pago_compras_internet_contra_entrega_terminal_de_pago',
            # 'medio_pago_compras_internet_otro',
            # 'tecnologia_predominante_proceso_produccion',
            # 'fuente_energia_utiliza_electricidad', 'fuente_energia_utiliza_diesel',
            # 'fuente_energia_utiliza_carbon', 'fuente_energia_utiliza_gas_natural',
            # 'fuente_energia_utiliza_gas_licuado', 'fuente_energia_utiliza_otro',
            # 'porcentaje_utiliza_capacidad_instalada_2014', 'modalidad_venta_2014',
            # 'realiza_estudios_mercado_para_promocion_producto_servicio_2014',
            # 'realiza_ventas_internet_2014', 'porcentaje_ventas_internet_2014',

            # 03_MÓDULO_IV_2
            # 'realiza_ventas_internet_exterior_2014',
            # 'contrato_servicios_asesoria_juridica',
            # 'contrato_servicios_asesoria_economica_financiera',
            # 'contrato_servicios_auditoria_contable_financiera',
            # 'contrato_servicios_contabilidad_asesoria_contable',
            # 'contrato_servicios_soporte_informatico',
            # 'contrato_servicios_mensajeria',
            # 'contrato_servicios_alquiler_maquinaria_mantenimiento',
            # 'contrato_servicios_limpieza', 'contrato_servicios_cobro_clientes',
            # 'contrato_servicios_asistencia_temas_ambientales',
            # 'contrato_servicios_tramites_aduana',
            # 'contrato_servicios_etiquetado_empaquetado_embalaje',
            # 'contrato_servicios_marketing', 'contrato_servicios_seguridad',
            # 'contrato_servicios_otro', 'contrato_servicios_otro_respuesta_abierta',

            # 04_MÓDULO_V_VI_1
            # 'dispone_computadora_escritorio',
            # 'cantidad_computadora_escritorio', 'antiguedad_computadora_escritorio',
            # 'dispone_computadora_portatil', 'cantidad_computadora_portatil',
            # 'antiguedad_computadora_portatil', 'dispone_multifuncional',
            # 'cantidad_multifuncional', 'antiguedad_multifuncional',
            # 'dispone_impresora', 'cantidad_impresora', 'antiguedad_impresora',
            # 'dispone_escaner', 'cantidad_escaner', 'antiguedad_escaner',
            # 'dispone_smartphone', 'cantidad_smartphone', 'antiguedad_smartphone',
            # 'otro_dispone', 'otro_dispone_especifique', 'cantidad_otro_dispone',
            # 'antiguedad_otro_dispone', 'utiliza_pagina_web',
            # 'utiliza_redes_sociales', 'utiliza_linkedin', 'tiene_software_contable',
            # 'tiene_software_ventas', 'tiene_software_personal',
            # 'tiene_software_finanzas', 'tiene_software_logistica',
            # 'tiene_software_produccion', 'tiene_software_soporte_informatico',
            # 'tiene_software_otro', 'tiene_software_otro_especifique',
            # 'tiene_software_ninguno',
            # 'porcentaje_trabajadores_utiliza_computadoras',
            # 'porcentaje_trabajadores_utiliza_servicio_internet',
            # 'utiliza_internet_para_busqueda_productos_servicios',
            # 'utiliza_internet_para_busqueda_organismos_gubernamentales',
            # 'utiliza_internet_para_busqueda_informacion_investigacion_desarrollo',
            # 'utiliza_internet_para_otra_busqueda_informacion',
            # 'utiliza_internet_para_comunicaciones',
            # 'utiliza_internet_para_operaciones_banca_elecctronica',
            # 'utiliza_internet_para_tramites_organismos_gubernamentales',
            # 'utiliza_internet_para_servicio_soporte_cliente',
            # 'utiliza_internet_para_ventas_bienes_servicios',
            # 'utiliza_internet_para_promocionar_productos_servicios',
            # 'utiliza_internet_para_capacitacion_personal',
            # 'utiliza_internet_para_video_conferencia',
            # 'utiliza_internet_para_emision_facturas_electronicas',
            # 'utiliza_internet_para_servicios_computacion_nube',
            # 'utiliza_internet_otro',
            # 'razon_no_servicio_internet_no_necesita_no_utilidad_empresa',
            # 'razon_no_servicio_internet_desconoce_usarlo',
            # 'razon_no_servicio_internet_no_rentable_caro',
            # 'razon_no_servicio_internet_no_seguro',
            # 'razon_no_servicio_internet_otro',
            # 'razon_no_dispone_computadoras_no_necesita_no_utilidad_empresa',
            # 'razon_no_dispone_computadoras_desconoce_usarlo',
            # 'razon_no_dispone_computadoras_no_rentable_caro',
            # 'razon_no_dispone_computadoras_otro',
            # 'empresa_dispuso_telefonos_moviles',

            # 04_MÓDULO_V_VI_2
            # 'utiliza_servicio_correo_postal_2014',
            'realiza_exportaciones_2014',
            'dificultad_exportar_falta_informacion_procesos',
            'dificultad_exportar_costos_logisticos',
            'dificultad_exportar_identificacion_mercados_compradores',
            'dificultad_exportar_acceso_financiamiento_operaciones',
            'dificultad_exportar_cumplir_normas_requisitos_calidad',
            'dificultad_exportar_cumplir_requisitos_cantidad_compradores',
            'dificultad_exportar_retrasos_causados_transporte',
            'dificultad_exportar_procedimientos_aduaneros',
            'dificultad_exportar_retrasos_aduana',
            'dificultad_exportar_barreras_arancelarias_extranjero',
            'dificultad_exportar_corrupcion_fronteras',
            'dificultad_exportar_ninguna',

            #05_MÓDULO_VII_VIII_IX
            'criterio_elegir_credito_prestamo_tasas_interes',
            'criterio_elegir_credito_prestamo_plazo_pago',
            'criterio_elegir_credito_prestamo_garantias_solicitadas',
            'criterio_elegir_credito_prestamo_prestigio_entidad_financiera',
            'criterio_elegir_credito_prestamo_recomendacion_terceros',
            'criterio_elegir_credito_prestamo_beneficios_entidad',
            'criterio_elegir_credito_prestamo_rapidez_otorgamiento',
            'criterio_elegir_credito_prestamo_periodo_gracia',
            'criterio_elegir_credito_prestamo_otro',
            # 'duracion_contrato_trabajadores_2014',
            # 'califica_requisitos_mtpe_contratacion_trabajadores_plazo_fijo',
            # 'n_trabajadores_promedio_plazo_indeterminado',
            # 'califica_requisitos_mtpe_contratacion_trabajadores_plazo_indeterminado',
            # 'conocimiento_minimo_requerido_trabajadores_discapacidad_contratar',
            # 'califica_porcentaje_contratacion_personas_discapacidad',
            # 'califica_exigencias_infraestructura_personas_discapacidad',
            # 'califica_cumplimiento_empresas_obligaciones_seguridad_salud',
            # 'califica_requisitos_tercerizacion_laboral_empresas',
            # 'afecta_decision_contratar_pago_beneficios_sociales_tercerizacion_laboral',
            # 'califica_cumplimiento_obligaciones_proteccion_maternidad',
            # 'conoce_sunafil',
            # 'califica_labor_fiscalizacion_regulacion_laboral_sunafil',
            # 'cuenta_instrumentos_gestion_ambiental',
            # 'motivo_aplicar_instrumentos_gestion_ambiental_su_rubro',
            # 'motivo_aplicar_instrumentos_gestion_ambiental_su_rubro_respuesta_abierta',
            # 'califica_procedimientos_obtencion_declaracion_impacto_ambiental',
            # 'califica_procedimientos_obtencion_estudio_impacto_ambiental',
            # 'califica_procedimientos_obtencion_declaracion_ambiental_actividades_curso',
            # 'califica_procedimientos_obtencion_programa_adecuacion_manejo_ambiental',
            # 'califica_actividades_fiscalizacion_sancion_materia_regulacion_ambiental_2014',
            # 'califica_actividades_fiscalizacion_sancion_materia_regulacion_ambiental_oefa',
            # 'califica_actividades_fiscalizacion_sancion_materia_regulacion_ambiental_osinfor',
            # 'califica_actividades_fiscalizacion_sancion_materia_regulacion_ambiental_gobierno_regional',
            # 'regimen_tributario_empresa_2014',
            # 'regimen_tributario_empresa_2014_respuesta_abierta',
            # 'califica_procedimientos_obligacion_impuestos_nacionales',
            # 'califica_procedimientos_pago_tributo_municipal',
            # 'califica_actividades_fiscalizacion_sancion_materia_tributos_nacionales_2014',
            # 'califica_actividades_fiscalizacion_sancion_materia_tributos_municipalidad_jurisdiccion_2014',
            # 'dias_demora_obtener_licencia_funcionamiento',
            # 'califica_procedimientos_obtencion_licencia_funcionamimento',
            # 'ha_solicitado_autorizacion_sectorial',
            # 'califica_procedimientos_obtencion_autorizacion_sectorial',
            # 'requerimientos_diferente_permiso_sectorial_pago',
            # 'obtuvo_certificado_seguridad_defensa_civil',
            # 'dias_demora_obtener_certificado_seguridad_defensa_civil',
            # 'tipo_certificado_seguridad_defensa_civil',
            # 'califica_procedimiento_obtener_certificado_seguridad_defensa_civil',
            # 'empresa_atendio_inspeccion_tecnicas_seguridad_defensa_civil',
            # 'factor_limita_crecimiento_empresa_financiamiento',
            # 'factor_limita_crecimiento_empresa_proceso_productivo_poco_automatizado',
            # 'factor_limita_crecimiento_empresa_falta_mano_obra_calificada',
            # 'factor_limita_crecimiento_empresa_falta_repuesto_servicio_tecnico_maquinaria',
            # 'factor_limita_crecimiento_empresa_demanda_limitada',
            # 'factor_limita_crecimiento_empresa_falta_insumos_nacionales',
            # 'factor_limita_crecimiento_empresa_falta_insumos_importados',
            # 'factor_limita_crecimiento_empresa_falta_energia_electrica',
            # 'factor_limita_crecimiento_empresa_falta_informacion_tecnologica',
            # 'factor_limita_crecimiento_empresa_falta_informacion_mercados',
            # 'factor_limita_crecimiento_empresa_excesiva_regulacion_laboral',
            # 'factor_limita_crecimiento_empresa_excesiva_regulacion_tributaria',
            # 'factor_limita_crecimiento_empresa_excesiva_regulacion_ambiental',
            # 'factor_limita_crecimiento_empresa_excesiva_regulacion_licencia_funcionamiento_construccion',
            # 'factor_limita_crecimiento_empresa_excesiva_regulacion_defensa_civil',
            # 'factor_limita_crecimiento_empresa_excesiva_regulacion_tramites_sectoriales_autorizaciones',
            # 'factor_limita_crecimiento_empresa_corrupcion_funcionarios_publicos',
            # 'factor_limita_crecimiento_empresa_contrabando',
            # 'factor_limita_crecimiento_empresa_exceso_cargas_tributarias',
            # 'factor_limita_crecimiento_empresa_informalidad',
            # 'factor_limita_crecimiento_empresa_otro',
            # 'factor_limita_crecimiento_empresa_ninguno'
            ]
        )

        return [
          transform_step_01, 
          transform_step_02_01, 
          transform_step_02_02, 
          # transform_step_03_01, 
          # transform_step_03_02,
          # transform_step_04_01,
          transform_step_04_02,
          transform_step_05,
          join_step, 
          load_step
          ]

if __name__ == '__main__':
   pp = EncuestaEmpresasPipeline()
   pp.run({})