COLUMNS_RENAME = {
    'año': 'year',
    'indicador': 'indicator_id',
    'categoría': 'category_id'
}

INDUSTRY_REPLACE = {
    'Agricultura, ganadería, caza y actividades de servicios conexas': '01',
    'Silvicultura y extracción de madera': '02',
    'Pesca y acuicultura': '03',
    'Extracción de carbón de piedra y lignito': '05',
    'Extracción de petróleo crudo y gas natural': '06',
    'Extracción de minerales metalíferos': '07',
    'Explotación de otras minas y canteras': '08',
    'Actividades de servicios de apoyo para la explotación de minas y canteras': '09',
    'Elaboración de productos alimenticios': '10',
    'Elaboración de bebidas': '11',
    'Elaboración de productos de tabaco': '12',
    'Fabricación de productos textiles': '13',
    'Fabricación de prendas de vestir': '14',
    'Fabricación de productos de cuero y productos conexos': '15',
    'Producción de madera y fabricación de productos de madera y corcho, excepto muebles; fabricación de artículos de paja y de materiales trenzables': '16',
    'Fabricación de papel y de productos de papel': '17',
    'Impresión y reproducción de grabaciones': '18',
    'Fabricación de coque y productos de la refinación del petróleo': '19',
    'Fabricación de sustancias y productos químicos': '20',
    'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico': '21',
    'Fabricación de productos de caucho y de plástico': '22',
    'Fabricación de otros productos minerales no metálicos': '23',
    'Fabricación de metales comunes': '24',
    'Fabricación de productos elaborados de metal, excepto maquinaria y equipo': '25',
    'Fabricación de productos de informática, de electrónica y de óptica': '26',
    'Fabricación de equipo eléctrico': '27',
    'Fabricación de maquinaria y equipo n.c.p.': '28',
    'Fabricación de vehículos automotores, remolques y semirremolques': '29',
    'Fabricación de otro equipo de transporte': '30',
    'Fabricación de muebles': '31',
    'Otras industrias manufactureras': '32',
    'Reparación e instalación de maquinaria y equipo': '33',
    'Suministro de electricidad, gas, vapor y aire acondicionado': '35',
    'Captación, tratamiento y distribución de agua': '36',
    'Evacuación de aguas residuales': '37',
    'Recogida, tratamiento y eliminación de desechos; recuperación de materiales': '38',
    'Actividades de descontaminación y otros servicios de gestión de desechos': '39',
    'Construcción de edificios': '41',
    'Obras de ingeniería civil': '42',
    'Actividades especializadas de construcción': '43',
    'Comercio al por mayor y al por menor y reparación de vehículos automotores y motocicletas': '45',
    'Comercio al por mayor, excepto el de vehículos automotores y motocicletas': '46',
    'Comercio al por menor, excepto el de vehículos automotores y motocicletas': '47',
    'Transporte por vía terrestre y transporte por tuberías': '49',
    'Transporte por vía acuática': '50',
    'Transporte por vía aérea': '51',
    'Almacenamiento y actividades de apoyo al transporte': '52',
    'Actividades postales y de mensajería': '53',
    'Actividades de alojamiento': '55',
    'Actividades de servicio de comidas y bebidas': '56',
    'Actividades de edición': '58',
    'Actividades de producción de películas cinematográficas, vídeos y programas de televisión, grabación de sonido y edición de música': '59',
    'Actividades de programación y transmisión': '60',
    'Telecomunicaciones': '61',
    'Programación informática, consultoría de informática y actividades conexas': '62',
    'Actividades de servicios de información': '63',
    'Actividades de servicios financieros, excepto las de seguros y fondos de pensiones': '64',
    'Seguros, reaseguros y fondos de pensiones, excepto planes de seguridad social de afiliación obligatoria': '65',
    'Actividades auxiliares de las actividades de servicios financieros': '66',
    'Actividades inmobiliarias': '68',
    'Actividades jurídicas y de contabilidad': '69',
    'Actividades de oficinas principales; actividades de consultoría de gestión': '70',
    'Actividades de arquitectura e ingeniería; ensayos y análisis técnicos': '71',
    'Investigación científica y desarrollo': '72',
    'Publicidad y estudios de mercado': '73',
    'Otras actividades profesionales, científicas y técnicas': '74',
    'Actividades veterinarias': '75',
    'Actividades de alquiler y arrendamiento': '77',
    'Actividades de empleo': '78',
    'Actividades de agencias de viajes y operadores turísticos y servicios de reservas y actividades conexas': '79',
    'Actividades de seguridad e investigación': '80',
    'Actividades de servicios a edificios y de paisajismo': '81',
    'Actividades administrativas y de apoyo de oficina y otras actividades de apoyo a las empresas': '82',
    'Administración pública y defensa; planes de seguridad social de afiliación obligatoria': '84',
    'Enseñanza': '85',
    'Actividades de atención de la salud humana': '86',
    'Actividades de atención en instituciones': '87',
    'Actividades de asistencia social sin alojamiento': '88',
    'Actividades creativas, artísticas y de entretenimiento': '90',
    'Actividades de bibliotecas, archivos y museos y otras actividades culturales': '91',
    'Actividades de juegos de azar y apuestas': '92',
    'Actividades deportivas, de esparcimiento y recreativas': '93',
    'Actividades de asociaciones': '94',
    'Reparación de ordenadores y de efectos personales y enseres domésticos': '95',
    'Otras actividades de servicios personales': '96',
    'Actividades de los hogares como empleadores de personal doméstico': '97',
    'Actividades no diferenciadas de los hogares como productores de bienes y servicios para uso propio': '98',
    'Actividades de organizaciones y órganos extraterritoriales': '99',
    'No determinado': '00'
}

INDUSTRY_EXCEPTIONS = {
    'Fabricación de cueros y productos conexos': '15',
    'Producción de madera y fabricación de productos de madera y corcho; excepto muebles, fabricación de artículos de paja y de materiales trenzables': '16',
    'Actividades de impresión y reproducción de grabaciones': '18',
    'Fabricación de coque y de productos de la refinación del petróleo': '19',
    'Fabricación de productos farmacéuticos y preparaciones farmacéuticas': '21',
    'Fabricación de productos de caucho y plástico': '22',
    'Fabricación de productos informáticos, electrónicos y ópticos': '26',
    'Fabricación de maquinaria y equipo': '28',
    'Fabricación de otros tipos de equipo de transporte': '30',
    'Reparación e instalación de la maquinaria y equipo': '33',
    'Telecomunciaciones': '61',
    'Programación, consultoría y otras actividades relacionadas con la informática': '62',
    'Actividades de las sedes centrales, actividades de consultoría de gestión empresarial': '70',
    'Actividades de arquitectura e ingeniería, ensayos y análisis técnicos': '71',
    'Publicidad e investigación de mercados': '73'    
}
