DISTRICT_REPLACE_3 = {
 'Santiago De Surco' : "Santiago de Surco",
 'San Jeronimo' : "San Jerónimo",
 'Villa Maria Del Triunfo' : "Villa María del Triunfo",
 'Jesus Maria' : "Jesús María",
 'Magdalena Del Mar' : "Magdalena del Mar",
 'San Juan De Lurigancho' : "San Juan de Lurigancho",
 'Jose Luis Bustamante Y Rivero' : "José Luis Bustamante Y Rivero",
 'San Martin De Porres' : "San Martín de Porres",
 'N/D' : "Otro",
 'Belen' : "Belén",
 'San Vicente De Cañete' : "San Vicente de Cañete",
 'San Juan De Miraflores' : "San Juan de Miraflores",
 'Rimac' : "Rímac",
 'Simon Bolivar' : "Simon Bolívar",
 'Ancon' : "Ancón",
 'Santa Maria Del Mar' : "Santa María del Mar",
 'Los Baños Del Inca' : "Los Baños del Inca",
 'Jesus Nazareno' : "Jesús Nazareno",
 'Veintiseis De Octubre' : "Veintiseis de Octubre",
 'Azangaro' : "Azángaro",
 'Jose Leonardo Ortiz' : "José Leonardo Ortiz",
 'Coronel Gregorio Albarracin Lanchipa' : "Coronel Gregorio Albarracín Lanchipa",
 'No Aplica' : "Otro",

}