DISTRICT_REPLACE_2 = {
    'Villa el Salvador' : "Villa El Salvador",
     'Chepén ' : "Chepen",
     'Banda de Shilcayo' : "La Banda de Shilcayo",
     'La Victoria ' : "La Victoria",
     'La Esperanza ' : "La Esperanza",
     'Moyobamba ' : "Moyobamba",
     'San Martin de Porres' : "San Martín de Porres",
     'Ayavirí' : "Ayaviri",
     'Ventanilla ' : "Ventanilla",
     'Ferreñafe ' : "Ferreñafe",
     'Juanjui': "Juanjuí",
     'La Perla ': "La Perla",
     'MIraflores': "Miraflores",
     'Villa María del Triunfo ': "Villa María del Triunfo",
     '26 de Octubre': "Veintiseis de Octubre",
     'Independencia ': "Independencia",
     'Chiclayo ': "Chiclayo",
     'Veintiseis de octubre': "Veintiseis de Octubre",
     'Ate ': "Ate",
     'Cayma ': "Cayma",
     'Castilla ': "Castilla",
     'Gregorio Albarracín': "Coronel Gregorio Albarracín Lanchipa",
     'Chepén' : "Chepen",
     'Ica ' : "Ica",
     'Callao ' : "Callao",
     'Huancayo ' : "Huancayo",
     'Pillo Marca' : "Pillco Marca",
     'Callería' : "Calleria",
     'Nuevo chimbote' : "Nuevo Chimbote",
     'La banda de Silchayo' : "La Banda de Shilcayo",
     'Ate Vitarte' : "Ate",
     'Pardo Miguel Naranjos' : "Pardo Miguel",
     'Huacho Mariscal Castilla N°400 (Interior 3) Huacho' : "Huacho",
     'Huánuco' : "Huanuco",
     'Juliaca ' : "Juliaca",
     'Jesus María' : "Jesús María",
     'Ascención' : "Asunción",
     'LIMA' : "Lima",
     'San Sebastián' : "San Sebastian",
     'José Luis Bustamante y Rivero' : "José Luis Bustamante Y Rivero",

}